import { StyleSheet } from 'react-native';
import { spacing } from '../../../src/theme/spacing';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F9F8F6',
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
  },
  heroCard: {
    borderRadius: 32,
    padding: 24,
    marginBottom: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 4,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  heroDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#22C55E',
    marginRight: 6,
  },
  heroBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#16A34A',
    letterSpacing: 1.5,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: '#111827',
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  heroTitleAccent: {
    color: '#22C55E',
  },
  heroSubtitle: {
    fontSize: 13,
    color: '#4B5563',
    lineHeight: 18,
    fontWeight: '500',
  },
  tabsRow: {
    flexDirection: 'row',
    backgroundColor: '#111827',
    borderRadius: 20,
    padding: 6,
    marginBottom: 20,
  },
  tabPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    paddingVertical: 10,
  },
  tabPillActive: {
    backgroundColor: '#374151',
  },
  tabPillText: {
    marginLeft: 6,
    fontSize: 12,
    fontWeight: '800',
    color: '#9CA3AF',
  },
  tabPillTextActive: {
    color: '#FFFFFF',
  },
  section: {
    marginBottom: 40,
  },
  cardWide: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E2E0DA',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionHeaderIcon: {
    width: 32,
    height: 32,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DCFCE7',
    marginRight: 12,
  },
  sectionHeaderTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#111827',
  },
  mainSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputMainWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F4F0',
    borderRadius: 15,
    paddingHorizontal: 16,
    height: 52,
    borderWidth: 1,
    borderColor: '#E2E0DA',
  },
  inputMain: {
    flex: 1,
    marginLeft: 10,
    fontSize: 14,
    color: '#111827',
    fontWeight: '600',
  },
  analyserBtn: {
    marginLeft: 12,
    borderRadius: 15,
    width: 100,
    height: 52,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  analyserText: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  hrScrollArea: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#F5F4F0',
    paddingTop: 16,
  },
  hrListTitle: {
    fontSize: 10,
    fontWeight: '900',
    color: '#9A9A94',
    letterSpacing: 2,
    marginBottom: 12,
  },
  hrScrollContent: {
    paddingBottom: 4,
  },
  hrMiniCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 12,
    marginRight: 10,
    width: 130,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
  },
  hrMiniCardActive: {
    borderColor: '#22C55E',
    backgroundColor: '#F0FDF4',
  },
  hrIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E2E0DA',
  },
  hrName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  checkDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#22C55E',
  },
  emptyHr: {
    fontSize: 12,
    color: '#9CA3AF',
    fontStyle: 'italic',
  },
  paramsCard: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E0DA',
  },
  paramsTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#111827',
    marginLeft: 10,
  },
  fieldBlock: {
    marginTop: 16,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#9CA3AF',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  segmentRow: {
    flexDirection: 'row',
    backgroundColor: '#F5F4F0',
    borderRadius: 12,
    padding: 4,
  },
  segment: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 10,
  },
  segmentActive: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  segmentText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '700',
  },
  segmentActiveText: {
    fontSize: 12,
    color: '#111827',
    fontWeight: '900',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F4F0',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E0DA',
    paddingHorizontal: 16,
    height: 48,
  },
  input: {
    flex: 1,
    marginLeft: 10,
    fontSize: 13,
    color: '#111827',
    fontWeight: '600',
  },
  primaryBtn: {
    marginTop: 24,
    borderRadius: 15,
    height: 56,
    backgroundColor: '#6366F1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#6366F1',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  primaryBtnText: {
    marginLeft: 10,
    fontSize: 14,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    flex: 1,
    padding: 24,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalBranding: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalLogo: {
    width: 24,
    height: 24,
    marginRight: 10,
  },
  modalBrandTxt: {
    fontSize: 11,
    fontWeight: '900',
    color: '#D4AF37',
    letterSpacing: 2,
  },
  closeModalBtn: {
    padding: 4,
  },
  draftScroll: {
    paddingBottom: 40,
  },
  subjectBox: {
    backgroundColor: '#F9FAFB',
    borderRadius: 15,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  subjectLabel: {
    fontSize: 10,
    fontWeight: '900',
    color: '#6366F1',
    marginBottom: 4,
  },
  subjectText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#111827',
  },
  bodyBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowRadius: 10,
  },
  bodyText: {
    fontSize: 15,
    lineHeight: 24,
    color: '#374151',
    fontWeight: '500',
  },
  aiTag: {
    marginTop: 20,
    fontSize: 9,
    fontWeight: '900',
    color: '#D1D5DB',
    textAlign: 'center',
    letterSpacing: 1.5,
  },
  copyBtn: {
    borderRadius: 15,
    overflow: 'hidden',
  },
  copyBtnGrad: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  copyBtnTxt: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFFFFF',
    marginLeft: 10,
    letterSpacing: 1,
  },
  cancelLink: {
    marginTop: 20,
    alignItems: 'center',
  },
  cancelLinkText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#9CA3AF',
    textDecorationLine: 'underline',
  },
  carnetHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  carnetTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#111827',
  },
  carnetTitleAccent: {
    color: '#22C55E',
  },
  carnetSubtitle: {
    fontSize: 13,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  actualiserBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E0DA',
  },
  actualiserText: {
    marginLeft: 6,
    fontSize: 12,
    fontWeight: '700',
    color: '#111827',
  },
  carnetGrid: {
    rowGap: 16,
  },
  carnetCard: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#E2E0DA',
  },
  carnetCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  carnetIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F5F4F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  carnetCompany: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  carnetSync: {
    fontSize: 11,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  tagRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  tagPill: {
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  tagText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#4F46E5',
    letterSpacing: 1,
  },
  contactDetailsArea: {
    borderTopWidth: 1,
    borderTopColor: '#F5F4F0',
    paddingTop: 12,
    gap: 8,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contactVal: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4B5563',
    marginLeft: 10,
  },
  linkText: {
    color: '#6366F1',
    textDecorationLine: 'underline',
  },
  carnetActionBtn: {
    marginTop: 16,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#6366F1',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  carnetActionBtnGrad: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
  },
  carnetActionBtnTxt: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  emptyCarnet: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyCarnetText: {
    marginTop: 16,
    fontSize: 14,
    color: '#9CA3AF',
    fontWeight: '600',
  },
});

// Expo Router route placeholder to silence route warning for style-only files.
const _RoutePlaceholder = () => null;
export default _RoutePlaceholder;

