import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#000',
  },
  camera: { 
    ...StyleSheet.absoluteFillObject,
  },
  vignette: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  headerOverlay: {
    position: 'absolute',
    top: 0, 
    left: 0, 
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    zIndex: 10,
  },
  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  recruiterAvatar: {
    width: 36, 
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(99, 102, 241, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recruiterName: { 
    color: '#FFF', 
    fontSize: 15, 
    fontWeight: '700',
  },
  callMeta: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 6, 
    marginTop: 2,
  },
  liveBadge: { 
    width: 6, 
    height: 6, 
    borderRadius: 3, 
    backgroundColor: '#10B981',
  },
  callTime: { 
    color: '#D1D5DB', 
    fontSize: 12, 
    fontWeight: '600', 
    fontVariant: ['tabular-nums'],
  },
  flipButton: {
    width: 44, 
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center', 
    justifyContent: 'center',
    borderWidth: 1, 
    borderColor: 'rgba(255,255,255,0.1)',
  },
  chatOverlay: {
    position: 'absolute',
    bottom: 140, 
    left: 16, 
    right: 16,
    maxHeight: 300,
    zIndex: 10,
  },
  chatScroll: { 
    paddingBottom: 10, 
    gap: 10,
  },
  messageBubble: {
    maxWidth: '85%',
    padding: 14,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  bubbleUser: { 
    alignSelf: 'flex-end', 
    backgroundColor: 'rgba(79, 70, 229, 0.7)', 
    borderColor: 'rgba(99, 102, 241, 0.4)',
  },
  bubbleRecruiter: { 
    alignSelf: 'flex-start',
  },
  messageName: { 
    color: '#A5B4FC', 
    fontSize: 11, 
    fontWeight: '800', 
    marginBottom: 4, 
    textTransform: 'uppercase',
  },
  messageText: { 
    color: '#FFF', 
    fontSize: 14, 
    lineHeight: 20,
  },
  thinkingIndicator: {
    alignSelf: 'flex-start',
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 8,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 16, 
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1, 
    borderColor: 'rgba(255,255,255,0.1)',
  },
  thinkingText: { 
    color: '#A5B4FC', 
    fontSize: 13, 
    fontWeight: '600',
  },
  bottomControls: {
    position: 'absolute',
    bottom: 0, 
    left: 0, 
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 40,
    zIndex: 10,
  },
  controlButton: {
    width: 56, 
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center', 
    justifyContent: 'center',
  },
  controlButtonDummy: { 
    width: 56,
  },
  endCallButton: { 
    backgroundColor: '#EF4444',
  },
  mainMicButton: {
    width: 80, 
    height: 80,
    borderRadius: 40,
    backgroundColor: '#4F46E5',
    alignItems: 'center', 
    justifyContent: 'center',
    shadowColor: '#4F46E5', 
    shadowOpacity: 0.5, 
    shadowRadius: 15, 
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  mainMicButtonActive: { 
    backgroundColor: '#EF4444', 
    shadowColor: '#EF4444',
  },
  pulseRing: {
    position: 'absolute',
    top: -10,
    bottom: -10,
    left: -10,
    right: -10,
    borderRadius: 50,
    borderWidth: 2, 
    borderColor: '#EF4444',
    opacity: 0.5,
  },
  recruiterMainView: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000',
  },
  fullScreenImage: {
    width: '100%',
    height: '100%',
    opacity: 0.9,
  },
  thinkingGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(99, 102, 241, 0.15)',
    borderWidth: 4,
    borderColor: 'rgba(165, 180, 252, 0.3)',
  },
  userCameraPIP: {
    position: 'absolute',
    top: 100,
    right: 20,
    width: 110,
    height: 160,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#1A1A18',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    zIndex: 20,
    shadowColor: '#000',
    shadowOpacity: 0.5,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  cameraFill: {
    width: '100%',
    height: '100%',
  },
  cameraPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  recruiterAvatarSmall: {
    width: 36, 
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(99, 102, 241, 0.4)',
  },
  callingOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  callingContent: {
    alignItems: 'center',
    gap: 16,
  },
  callingAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  callingName: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
  },
  callingStatus: {
    color: '#A5B4FC',
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 1,
  },
});

// Expo Router route placeholder to silence route warning for style-only files.
const _RoutePlaceholder = () => null;
export default _RoutePlaceholder;

