import { StyleSheet } from 'react-native';
import { spacing } from '../../../src/theme/spacing';

export const mentorSimulatorStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F3EEE7',
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing['3xl'],
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#C4BDB0',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1A18',
  },
  headerTextBlock: {
    marginLeft: spacing.md,
    flex: 1,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#151515',
  },
  headerSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#5A554C',
  },
  historyLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A2E',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2D2D44',
    marginLeft: 12,
  },
  historyLinkText: {
    color: '#A5B4FC',
    fontSize: 12,
    fontWeight: '600',
  },
  hero: {
    padding: spacing.lg,
    borderRadius: 24,
    backgroundColor: '#F9E4C4',
    borderWidth: 1,
    borderColor: '#F0C98C',
    marginBottom: spacing.xl,
    shadowColor: 'rgba(0,0,0,0.08)',
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  heroTextContainer: {
    flex: 1,
  },
  heroPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    backgroundColor: '#F5C58A',
    marginBottom: spacing.sm,
  },
  heroPillText: {
    marginLeft: spacing.xs,
    fontSize: 11,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#5C3600',
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#161513',
    marginBottom: spacing.xs,
  },
  heroSubtitle: {
    fontSize: 14,
    color: '#5F584E',
    lineHeight: 20,
  },
  grid: {
    flexDirection: 'column',
    gap: spacing.xl,
    marginTop: spacing.lg,
  },
  leftColumn: {
    flex: 1,
  },
  rightColumn: {
    flex: 1,
  },
  fieldBlock: {
    marginBottom: spacing.lg,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4A4A46',
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 14,
    backgroundColor: '#F5F4F0',
    borderWidth: 1,
    borderColor: '#EAEAE6',
    shadowColor: 'rgba(0,0,0,0.03)',
    shadowOpacity: 1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  textInput: {
    flex: 1,
    marginLeft: spacing.sm,
    fontSize: 14,
    color: '#151515',
    paddingVertical: 4,
  },
  textAreaWrapper: {
    alignItems: 'flex-start',
  },
  textArea: {
    height: 96,
    textAlignVertical: 'top',
  },
  fieldHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  importButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E2E0DA',
    backgroundColor: '#FFFFFF',
  },
  importButtonText: {
    marginLeft: spacing.xs,
    fontSize: 12,
    fontWeight: '600',
    color: '#1A1A18',
  },
  recruiterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  recruiterCard: {
    flex: 1,
    borderRadius: 18,
    padding: spacing.md,
    backgroundColor: '#F7F4EE',
    borderWidth: 1,
    borderColor: '#EAEAE6',
    shadowColor: 'rgba(0,0,0,0.03)',
    shadowOpacity: 1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  recruiterCardActive: {
    borderColor: '#FF8C5A',
    backgroundColor: '#FFF0EB',
  },
  recruiterAvatarWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFE1B0',
    marginBottom: spacing.sm,
    position: 'relative',
    borderWidth: 1,
    borderColor: '#EAEAE6',
  },
  recruiterAvatarImg: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
  },
  recruiterOnlineDot: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: '#FFF0EB',
  },
  recruiterText: {
    marginRight: spacing.sm,
  },
  recruiterName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A1A18',
    marginBottom: 2,
  },
  recruiterRole: {
    fontSize: 11,
    color: '#6B7280',
  },
  recruiterCheck: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FF6B35',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formatRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  formatButton: {
    flex: 1,
    borderRadius: 999,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EAEAE6',
    backgroundColor: '#FFFFFF',
  },
  formatButtonActive: {
    borderColor: '#FF6B35',
    backgroundColor: '#FFF0EB',
  },
  formatButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
  },
  formatButtonTextActive: {
    color: '#1A1A18',
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.xl,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: '#E5E5E0',
  },
  soundButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#EAEAE6',
    backgroundColor: '#FFFFFF',
  },
  soundButtonText: {
    marginLeft: spacing.xs,
    fontSize: 13,
    fontWeight: '500',
    color: '#1A1A18',
  },
  launchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    backgroundColor: '#FF6B35',
  },
  launchButtonText: {
    marginLeft: spacing.xs,
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },

  conversationArea: {
    marginTop: spacing.xl,
    padding: spacing.lg,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EAEAE6',
    shadowColor: 'rgba(0,0,0,0.04)',
    shadowOpacity: 1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A1A18',
    marginBottom: spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  thinkingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  thinkingText: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '600',
  },

  messagesList: {
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  messageRow: {
    flexDirection: 'row',
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowRecruiter: {
    justifyContent: 'flex-start',
  },
  messageBubble: {
    maxWidth: '86%',
    borderRadius: 18,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
  },
  messageBubbleUser: {
    backgroundColor: '#FFF0EB',
    borderColor: '#FF8C5A',
  },
  messageBubbleRecruiter: {
    backgroundColor: '#F5F4F0',
    borderColor: '#EAEAE6',
  },
  messageBubbleSystem: {
    backgroundColor: '#F9E4C4',
    borderColor: '#F0C98C',
  },
  messageText: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  messageTextUser: {
    color: '#1A1A18',
  },
  messageTextRecruiter: {
    color: '#151515',
  },
  messageTextSystem: {
    color: '#5C3600',
  },

  replyRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.md,
  },
  replyInputWrapper: {
    flex: 1,
    paddingVertical: spacing.sm,
    alignItems: 'flex-start',
  },
  replyTextInput: {
    flex: 1,
    marginLeft: spacing.sm,
    fontSize: 14,
    color: '#151515',
    paddingVertical: 6,
    minHeight: 44,
    maxHeight: 120,
    textAlignVertical: 'top',
  },
  sendButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B35',
    borderWidth: 1,
    borderColor: '#FF6B35',
    elevation: 2,
  },
  micButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1F2937',
    borderWidth: 1,
    borderColor: '#111827',
    elevation: 2,
  },
  micButtonActive: {
    backgroundColor: '#DC2626',
    borderColor: '#B91C1C',
  },
  stopInterviewButton: {
    marginTop: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    backgroundColor: '#1A1A18',
    borderWidth: 1,
    borderColor: '#151515',
  },
  stopInterviewText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
});
