import { StyleSheet } from 'react-native';
import { spacing } from '../../../src/theme/spacing';

export const mentorAuditCvStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAFAF8',
  },
  container: {
    flex: 1,
    paddingHorizontal: spacing.xl,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.lg,
    marginBottom: spacing.lg,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EAEAE6',
    marginRight: spacing.md,
  },
  headerText: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A1A1A',
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#666666',
    marginTop: 2,
  },
  cvSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderWidth: 1,
    borderColor: '#EAEAE6',
    marginBottom: spacing.lg,
  },
  cvSummaryLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: spacing.md,
  },
  cvSummaryIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F5F5F3',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  cvSummaryInfo: {
    flex: 1,
  },
  cvSummaryLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: 2,
  },
  cvSummaryFile: {
    fontSize: 12,
    color: '#666666',
  },
  cvChangeButton: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#EAEAE6',
  },
  cvChangeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: spacing['2xl'],
    gap: spacing.xl,
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: '#EAEAE6',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: spacing.sm,
  },
  sectionBody: {
    fontSize: 13,
    color: '#666666',
    lineHeight: 18,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
  },
  chipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#047857',
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  scoreCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FFF0EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.lg,
  },
  scoreValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FF6B35',
  },
  scoreLabel: {
    fontSize: 11,
    color: '#9A9A94',
  },
  scoreInfo: {
    flex: 1,
  },
  scoreName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  scoreTitle: {
    fontSize: 13,
    color: '#4A4A46',
    marginTop: 2,
  },
  scoreDelta: {
    fontSize: 11,
    color: '#16A34A',
    marginTop: 6,
  },
  subScoresRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  subScoreCard: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    backgroundColor: '#F5F4F0',
  },
  subScoreLabel: {
    fontSize: 11,
    color: '#4A4A46',
  },
  subScoreValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  techSection: {
    marginTop: spacing.md,
  },
  techTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: spacing.xs,
  },
  techChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  techChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    backgroundColor: '#EFF6FF',
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  techChipText: {
    fontSize: 11,
    color: '#1D4ED8',
    fontWeight: '500',
  },
  subSectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: spacing.xs,
  },
  keywordsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  keywordChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#FFE0D1',
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    backgroundColor: '#FFF7ED',
  },
  keywordChipText: {
    fontSize: 11,
    color: '#9A3412',
    fontWeight: '500',
  },
  correctionCard: {
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: 12,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  correctionLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 2,
  },
  correctionTextOriginal: {
    fontSize: 12,
    color: '#9A9A94',
    marginTop: 2,
  },
  correctionTextNew: {
    fontSize: 12,
    color: '#111827',
    marginTop: 2,
    fontWeight: '600',
  },
  pdfButton: {
    marginTop: spacing.md,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B35',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: spacing.lg,
  },
  pdfButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  todoItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: spacing.xs,
  },
  todoBullet: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#F5D061',
    marginTop: 7,
    marginRight: spacing.sm,
  },
  todoText: {
    fontSize: 13,
    color: '#666666',
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.15)',
  },
  overlayCard: {
    width: '88%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: '#EAEAE6',
  },
  overlayHeader: {
    flexDirection: 'row',
    marginBottom: spacing.lg,
  },
  overlayIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F3',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  overlayHeaderText: {
    flex: 1,
  },
  overlayTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  overlaySubtitle: {
    fontSize: 13,
    color: '#666666',
  },
  choiceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#EAEAE6',
  },
  choiceLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  choiceTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  choiceSubtitle: {
    fontSize: 12,
    color: '#666666',
    marginTop: 2,
  },
  footerActions: {
    position: 'absolute',
    left: spacing.xl,
    right: spacing.xl,
    bottom: spacing.xl,
  },
  runAuditButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingVertical: 14,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 4,
  },
  runAuditButtonDisabled: {
    opacity: 0.5,
  },
  runAuditButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  templatePickerScroll: {
    marginBottom: spacing.md,
  },
  templateCard: {
    marginRight: 10,
    borderRadius: 10,
    padding: 12,
    minWidth: 120,
    alignItems: 'center',
  },
  templateCardActive: {
    borderWidth: 2,
  },
  templateCardInactive: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FAFAFA',
  },
  templateColorIndicator: {
    width: 28,
    height: 28,
    borderRadius: 14,
    marginBottom: 6,
  },
  templateLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1A1A1A',
    textAlign: 'center',
  },
  templateDescription: {
    fontSize: 10,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 2,
  },
});
