import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F172A', // Dark mode by default for premium feel
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 40 : 10,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#1E293B',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  headerTitleContainer: {
    flex: 1,
  },
  title: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFF',
  },
  titleHighlight: {
    color: '#F59E0B',
  },
  subtitle: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
  },
  scroll: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  pricingGrid: {
    gap: 24,
    marginBottom: 40,
  },
  tierCard: {
    backgroundColor: '#1E293B',
    borderRadius: 32,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
    position: 'relative',
    overflow: 'hidden',
  },
  tierCardHighlighted: {
    borderColor: '#F59E0B',
    backgroundColor: '#1E293B',
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
  },
  popularBadge: {
    position: 'absolute',
    top: -1,
    alignSelf: 'center',
  },
  popularBadgeGradient: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  popularBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: 1.5,
  },
  tierHeader: {
    marginBottom: 24,
    marginTop: 8,
  },
  iconContainer: {
    width: 60,
    height: 60,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.1)',
  },
  tierName: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFF',
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 12,
  },
  tierPrice: {
    fontSize: 42,
    fontWeight: '900',
    color: '#FFF',
    letterSpacing: -1,
  },
  tierPriceSub: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#94A3B8',
    marginLeft: 6,
    textTransform: 'uppercase',
  },
  tierDesc: {
    fontSize: 14,
    color: '#94A3B8',
    lineHeight: 20,
    fontWeight: '500',
  },
  featuresContainer: {
    gap: 16,
    marginBottom: 32,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  checkIconWrapper: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  crossIconWrapper: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#334155',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#475569',
  },
  horizontalLine: {
    width: 6,
    height: 2,
    backgroundColor: '#64748B',
    borderRadius: 1,
  },
  featureText: {
    fontSize: 14,
    color: '#E2E8F0',
    flex: 1,
    fontWeight: '600',
  },
  subscribeBtnWrapper: {
    width: '100%',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  subscribeBtn: {
    width: '100%',
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subscribeBtnNormal: {
    borderWidth: 1,
    borderColor: '#475569',
  },
  subscribeBtnHighlighted: {
    // Gradient handles background
  },
  subscribeBtnText: {
    fontSize: 14,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  subscribeBtnTextNormal: {
    color: '#FFF',
  },
  subscribeBtnTextHighlighted: {
    color: '#0F172A',
  },
  extraSettings: {
    gap: 20,
  },
  settingSection: {
    backgroundColor: '#1E293B',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
  },
  settingSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  sectionIconBg: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFF',
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  settingLabel: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: '600',
  },
  settingSubLabel: {
    color: '#64748B',
    fontSize: 11,
    marginTop: 2,
    maxWidth: 200,
  },
  settingValueText: {
    color: '#CBD5E1',
    fontSize: 12,
    fontWeight: 'bold',
    backgroundColor: '#334155',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  profileBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    padding: 15,
    borderRadius: 16,
    gap: 15,
    marginBottom: 15,
  },
  profileBadgeAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileBadgeAvatarText: {
    color: '#F59E0B',
    fontSize: 18,
    fontWeight: 'bold',
  },
  profileBadgeName: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: 'bold',
  },
  profileBadgeTier: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  deleteAccountBtn: {
    paddingVertical: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    borderRadius: 16,
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
  },
  deleteAccountBtnText: {
    color: '#F87171',
    fontSize: 12,
    fontWeight: 'bold',
  }
});
